package com.cul.culsite.dao;

import com.cul.culsite.dto.MActualProductDTO;
import com.cul.culsite.dto.MActualProductDTOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MActualProductDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    int countByExample(MActualProductDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    int deleteByExample(MActualProductDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mapId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    int insert(MActualProductDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    int insertSelective(MActualProductDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    List<MActualProductDTO> selectByExample(MActualProductDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    MActualProductDTO selectByPrimaryKey(String mapId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MActualProductDTO record, @Param("example") MActualProductDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MActualProductDTO record, @Param("example") MActualProductDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MActualProductDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ACTUAL_PRODUCT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MActualProductDTO record);
}