package com.cul.culsite.dao;

import com.cul.culsite.dto.MDefaultCardInfomationDTO;
import com.cul.culsite.dto.MDefaultCardInfomationDTOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MDefaultCardInfomationDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    int countByExample(MDefaultCardInfomationDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    int deleteByExample(MDefaultCardInfomationDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cardNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    int insert(MDefaultCardInfomationDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    int insertSelective(MDefaultCardInfomationDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    List<MDefaultCardInfomationDTO> selectByExample(MDefaultCardInfomationDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    MDefaultCardInfomationDTO selectByPrimaryKey(String cardNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MDefaultCardInfomationDTO record, @Param("example") MDefaultCardInfomationDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MDefaultCardInfomationDTO record, @Param("example") MDefaultCardInfomationDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MDefaultCardInfomationDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_DEFAULT_CARD_INFOMATION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MDefaultCardInfomationDTO record);
}