package com.cul.culsite.dao;

import com.cul.culsite.dto.MMemberLevelDTO;
import com.cul.culsite.dto.MMemberLevelDTOCriteria;
import com.cul.culsite.dto.MMemberLevelDTOKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MMemberLevelDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    int countByExample(MMemberLevelDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    int deleteByExample(MMemberLevelDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MMemberLevelDTOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    int insert(MMemberLevelDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    int insertSelective(MMemberLevelDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    List<MMemberLevelDTO> selectByExample(MMemberLevelDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    MMemberLevelDTO selectByPrimaryKey(MMemberLevelDTOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MMemberLevelDTO record, @Param("example") MMemberLevelDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MMemberLevelDTO record, @Param("example") MMemberLevelDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MMemberLevelDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_MEMBER_LEVEL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MMemberLevelDTO record);
}