package com.cul.culsite.dao;

import com.cul.culsite.dto.MOrderTxnDetailDTO;
import com.cul.culsite.dto.MOrderTxnDetailDTOCriteria;
import com.cul.culsite.dto.MOrderTxnDetailDTOKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MOrderTxnDetailDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    int countByExample(MOrderTxnDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    int deleteByExample(MOrderTxnDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MOrderTxnDetailDTOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    int insert(MOrderTxnDetailDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    int insertSelective(MOrderTxnDetailDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    List<MOrderTxnDetailDTO> selectByExample(MOrderTxnDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    MOrderTxnDetailDTO selectByPrimaryKey(MOrderTxnDetailDTOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MOrderTxnDetailDTO record, @Param("example") MOrderTxnDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MOrderTxnDetailDTO record, @Param("example") MOrderTxnDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MOrderTxnDetailDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_ORDER_TXN_DETAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MOrderTxnDetailDTO record);
}