package com.cul.culsite.dao;

import com.cul.culsite.dto.MReduceActivityDetailDTO;
import com.cul.culsite.dto.MReduceActivityDetailDTOCriteria;
import com.cul.culsite.dto.MReduceActivityDetailDTOKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MReduceActivityDetailDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    int countByExample(MReduceActivityDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    int deleteByExample(MReduceActivityDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MReduceActivityDetailDTOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    int insert(MReduceActivityDetailDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    int insertSelective(MReduceActivityDetailDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    List<MReduceActivityDetailDTO> selectByExample(MReduceActivityDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    MReduceActivityDetailDTO selectByPrimaryKey(MReduceActivityDetailDTOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MReduceActivityDetailDTO record, @Param("example") MReduceActivityDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MReduceActivityDetailDTO record, @Param("example") MReduceActivityDetailDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MReduceActivityDetailDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_REDUCE_ACTIVITY_DETAIL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MReduceActivityDetailDTO record);
}