package com.cul.culsite.dao;

import com.cul.culsite.dto.MWebServiceRequestContentDTO;
import com.cul.culsite.dto.MWebServiceRequestContentDTOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MWebServiceRequestContentDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    int countByExample(MWebServiceRequestContentDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    int deleteByExample(MWebServiceRequestContentDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String contentDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    int insert(MWebServiceRequestContentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    int insertSelective(MWebServiceRequestContentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    List<MWebServiceRequestContentDTO> selectByExample(MWebServiceRequestContentDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    MWebServiceRequestContentDTO selectByPrimaryKey(String contentDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MWebServiceRequestContentDTO record, @Param("example") MWebServiceRequestContentDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MWebServiceRequestContentDTO record, @Param("example") MWebServiceRequestContentDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MWebServiceRequestContentDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_CONTENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MWebServiceRequestContentDTO record);
}