package com.cul.culsite.dao;

import com.cul.culsite.dto.MWebserviceRequestLogDTO;
import com.cul.culsite.dto.MWebserviceRequestLogDTOCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MWebserviceRequestLogDTOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    int countByExample(MWebserviceRequestLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    int deleteByExample(MWebserviceRequestLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    int insert(MWebserviceRequestLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    int insertSelective(MWebserviceRequestLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    List<MWebserviceRequestLogDTO> selectByExample(MWebserviceRequestLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    MWebserviceRequestLogDTO selectByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MWebserviceRequestLogDTO record, @Param("example") MWebserviceRequestLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MWebserviceRequestLogDTO record, @Param("example") MWebserviceRequestLogDTOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MWebserviceRequestLogDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_WEBSERVICE_REQUEST_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MWebserviceRequestLogDTO record);
}