package com.cul.culsite.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MCardCategoryDTOCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public MCardCategoryDTOCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIssuerIdIsNull() {
            addCriterion("ISSUER_ID is null");
            return (Criteria) this;
        }

        public Criteria andIssuerIdIsNotNull() {
            addCriterion("ISSUER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIssuerIdEqualTo(String value) {
            addCriterion("ISSUER_ID =", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdNotEqualTo(String value) {
            addCriterion("ISSUER_ID <>", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdGreaterThan(String value) {
            addCriterion("ISSUER_ID >", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUER_ID >=", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdLessThan(String value) {
            addCriterion("ISSUER_ID <", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdLessThanOrEqualTo(String value) {
            addCriterion("ISSUER_ID <=", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdLike(String value) {
            addCriterion("ISSUER_ID like", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdNotLike(String value) {
            addCriterion("ISSUER_ID not like", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdIn(List<String> values) {
            addCriterion("ISSUER_ID in", values, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdNotIn(List<String> values) {
            addCriterion("ISSUER_ID not in", values, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdBetween(String value1, String value2) {
            addCriterion("ISSUER_ID between", value1, value2, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdNotBetween(String value1, String value2) {
            addCriterion("ISSUER_ID not between", value1, value2, "issuerId");
            return (Criteria) this;
        }

        public Criteria andCategoryNoIsNull() {
            addCriterion("CATEGORY_NO is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNoIsNotNull() {
            addCriterion("CATEGORY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNoEqualTo(String value) {
            addCriterion("CATEGORY_NO =", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoNotEqualTo(String value) {
            addCriterion("CATEGORY_NO <>", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoGreaterThan(String value) {
            addCriterion("CATEGORY_NO >", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NO >=", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoLessThan(String value) {
            addCriterion("CATEGORY_NO <", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NO <=", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoLike(String value) {
            addCriterion("CATEGORY_NO like", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoNotLike(String value) {
            addCriterion("CATEGORY_NO not like", value, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoIn(List<String> values) {
            addCriterion("CATEGORY_NO in", values, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoNotIn(List<String> values) {
            addCriterion("CATEGORY_NO not in", values, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoBetween(String value1, String value2) {
            addCriterion("CATEGORY_NO between", value1, value2, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNoNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_NO not between", value1, value2, "categoryNo");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNull() {
            addCriterion("CATEGORY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIsNotNull() {
            addCriterion("CATEGORY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryNameEqualTo(String value) {
            addCriterion("CATEGORY_NAME =", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotEqualTo(String value) {
            addCriterion("CATEGORY_NAME <>", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThan(String value) {
            addCriterion("CATEGORY_NAME >", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME >=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThan(String value) {
            addCriterion("CATEGORY_NAME <", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME <=", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameLike(String value) {
            addCriterion("CATEGORY_NAME like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotLike(String value) {
            addCriterion("CATEGORY_NAME not like", value, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameIn(List<String> values) {
            addCriterion("CATEGORY_NAME in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotIn(List<String> values) {
            addCriterion("CATEGORY_NAME not in", values, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME between", value1, value2, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryNameNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME not between", value1, value2, "categoryName");
            return (Criteria) this;
        }

        public Criteria andCategoryClzIsNull() {
            addCriterion("CATEGORY_CLZ is null");
            return (Criteria) this;
        }

        public Criteria andCategoryClzIsNotNull() {
            addCriterion("CATEGORY_CLZ is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryClzEqualTo(String value) {
            addCriterion("CATEGORY_CLZ =", value, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzNotEqualTo(String value) {
            addCriterion("CATEGORY_CLZ <>", value, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzGreaterThan(String value) {
            addCriterion("CATEGORY_CLZ >", value, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_CLZ >=", value, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzLessThan(String value) {
            addCriterion("CATEGORY_CLZ <", value, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_CLZ <=", value, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzLike(String value) {
            addCriterion("CATEGORY_CLZ like", value, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzNotLike(String value) {
            addCriterion("CATEGORY_CLZ not like", value, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzIn(List<String> values) {
            addCriterion("CATEGORY_CLZ in", values, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzNotIn(List<String> values) {
            addCriterion("CATEGORY_CLZ not in", values, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzBetween(String value1, String value2) {
            addCriterion("CATEGORY_CLZ between", value1, value2, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andCategoryClzNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_CLZ not between", value1, value2, "categoryClz");
            return (Criteria) this;
        }

        public Criteria andFaceValueIsNull() {
            addCriterion("FACE_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andFaceValueIsNotNull() {
            addCriterion("FACE_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andFaceValueEqualTo(Long value) {
            addCriterion("FACE_VALUE =", value, "faceValue");
            return (Criteria) this;
        }

        public Criteria andFaceValueNotEqualTo(Long value) {
            addCriterion("FACE_VALUE <>", value, "faceValue");
            return (Criteria) this;
        }

        public Criteria andFaceValueGreaterThan(Long value) {
            addCriterion("FACE_VALUE >", value, "faceValue");
            return (Criteria) this;
        }

        public Criteria andFaceValueGreaterThanOrEqualTo(Long value) {
            addCriterion("FACE_VALUE >=", value, "faceValue");
            return (Criteria) this;
        }

        public Criteria andFaceValueLessThan(Long value) {
            addCriterion("FACE_VALUE <", value, "faceValue");
            return (Criteria) this;
        }

        public Criteria andFaceValueLessThanOrEqualTo(Long value) {
            addCriterion("FACE_VALUE <=", value, "faceValue");
            return (Criteria) this;
        }

        public Criteria andFaceValueIn(List<Long> values) {
            addCriterion("FACE_VALUE in", values, "faceValue");
            return (Criteria) this;
        }

        public Criteria andFaceValueNotIn(List<Long> values) {
            addCriterion("FACE_VALUE not in", values, "faceValue");
            return (Criteria) this;
        }

        public Criteria andFaceValueBetween(Long value1, Long value2) {
            addCriterion("FACE_VALUE between", value1, value2, "faceValue");
            return (Criteria) this;
        }

        public Criteria andFaceValueNotBetween(Long value1, Long value2) {
            addCriterion("FACE_VALUE not between", value1, value2, "faceValue");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("PRODUCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("PRODUCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("PRODUCT_ID =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("PRODUCT_ID <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("PRODUCT_ID >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ID >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("PRODUCT_ID <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_ID <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("PRODUCT_ID like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("PRODUCT_ID not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("PRODUCT_ID in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("PRODUCT_ID not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("PRODUCT_ID between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_ID not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andStyleIsNull() {
            addCriterion("STYLE is null");
            return (Criteria) this;
        }

        public Criteria andStyleIsNotNull() {
            addCriterion("STYLE is not null");
            return (Criteria) this;
        }

        public Criteria andStyleEqualTo(String value) {
            addCriterion("STYLE =", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotEqualTo(String value) {
            addCriterion("STYLE <>", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleGreaterThan(String value) {
            addCriterion("STYLE >", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleGreaterThanOrEqualTo(String value) {
            addCriterion("STYLE >=", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLessThan(String value) {
            addCriterion("STYLE <", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLessThanOrEqualTo(String value) {
            addCriterion("STYLE <=", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleLike(String value) {
            addCriterion("STYLE like", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotLike(String value) {
            addCriterion("STYLE not like", value, "style");
            return (Criteria) this;
        }

        public Criteria andStyleIn(List<String> values) {
            addCriterion("STYLE in", values, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotIn(List<String> values) {
            addCriterion("STYLE not in", values, "style");
            return (Criteria) this;
        }

        public Criteria andStyleBetween(String value1, String value2) {
            addCriterion("STYLE between", value1, value2, "style");
            return (Criteria) this;
        }

        public Criteria andStyleNotBetween(String value1, String value2) {
            addCriterion("STYLE not between", value1, value2, "style");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountIsNull() {
            addCriterion("DEFAULT_USE_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountIsNotNull() {
            addCriterion("DEFAULT_USE_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountEqualTo(Long value) {
            addCriterion("DEFAULT_USE_COUNT =", value, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountNotEqualTo(Long value) {
            addCriterion("DEFAULT_USE_COUNT <>", value, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountGreaterThan(Long value) {
            addCriterion("DEFAULT_USE_COUNT >", value, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountGreaterThanOrEqualTo(Long value) {
            addCriterion("DEFAULT_USE_COUNT >=", value, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountLessThan(Long value) {
            addCriterion("DEFAULT_USE_COUNT <", value, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountLessThanOrEqualTo(Long value) {
            addCriterion("DEFAULT_USE_COUNT <=", value, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountIn(List<Long> values) {
            addCriterion("DEFAULT_USE_COUNT in", values, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountNotIn(List<Long> values) {
            addCriterion("DEFAULT_USE_COUNT not in", values, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountBetween(Long value1, Long value2) {
            addCriterion("DEFAULT_USE_COUNT between", value1, value2, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andDefaultUseCountNotBetween(Long value1, Long value2) {
            addCriterion("DEFAULT_USE_COUNT not between", value1, value2, "defaultUseCount");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgIsNull() {
            addCriterion("VERIFY_MSG is null");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgIsNotNull() {
            addCriterion("VERIFY_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgEqualTo(String value) {
            addCriterion("VERIFY_MSG =", value, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgNotEqualTo(String value) {
            addCriterion("VERIFY_MSG <>", value, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgGreaterThan(String value) {
            addCriterion("VERIFY_MSG >", value, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgGreaterThanOrEqualTo(String value) {
            addCriterion("VERIFY_MSG >=", value, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgLessThan(String value) {
            addCriterion("VERIFY_MSG <", value, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgLessThanOrEqualTo(String value) {
            addCriterion("VERIFY_MSG <=", value, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgLike(String value) {
            addCriterion("VERIFY_MSG like", value, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgNotLike(String value) {
            addCriterion("VERIFY_MSG not like", value, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgIn(List<String> values) {
            addCriterion("VERIFY_MSG in", values, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgNotIn(List<String> values) {
            addCriterion("VERIFY_MSG not in", values, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgBetween(String value1, String value2) {
            addCriterion("VERIFY_MSG between", value1, value2, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andVerifyMsgNotBetween(String value1, String value2) {
            addCriterion("VERIFY_MSG not between", value1, value2, "verifyMsg");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeIsNull() {
            addCriterion("CATEGORY_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeIsNotNull() {
            addCriterion("CATEGORY_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeEqualTo(String value) {
            addCriterion("CATEGORY_TYPE =", value, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeNotEqualTo(String value) {
            addCriterion("CATEGORY_TYPE <>", value, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeGreaterThan(String value) {
            addCriterion("CATEGORY_TYPE >", value, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_TYPE >=", value, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeLessThan(String value) {
            addCriterion("CATEGORY_TYPE <", value, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_TYPE <=", value, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeLike(String value) {
            addCriterion("CATEGORY_TYPE like", value, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeNotLike(String value) {
            addCriterion("CATEGORY_TYPE not like", value, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeIn(List<String> values) {
            addCriterion("CATEGORY_TYPE in", values, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeNotIn(List<String> values) {
            addCriterion("CATEGORY_TYPE not in", values, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeBetween(String value1, String value2) {
            addCriterion("CATEGORY_TYPE between", value1, value2, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryTypeNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_TYPE not between", value1, value2, "categoryType");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreIsNull() {
            addCriterion("CATEGORY_GENRE is null");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreIsNotNull() {
            addCriterion("CATEGORY_GENRE is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreEqualTo(String value) {
            addCriterion("CATEGORY_GENRE =", value, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreNotEqualTo(String value) {
            addCriterion("CATEGORY_GENRE <>", value, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreGreaterThan(String value) {
            addCriterion("CATEGORY_GENRE >", value, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_GENRE >=", value, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreLessThan(String value) {
            addCriterion("CATEGORY_GENRE <", value, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_GENRE <=", value, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreLike(String value) {
            addCriterion("CATEGORY_GENRE like", value, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreNotLike(String value) {
            addCriterion("CATEGORY_GENRE not like", value, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreIn(List<String> values) {
            addCriterion("CATEGORY_GENRE in", values, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreNotIn(List<String> values) {
            addCriterion("CATEGORY_GENRE not in", values, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreBetween(String value1, String value2) {
            addCriterion("CATEGORY_GENRE between", value1, value2, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryGenreNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_GENRE not between", value1, value2, "categoryGenre");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameIsNull() {
            addCriterion("CATEGORY_IS_REALNAME is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameIsNotNull() {
            addCriterion("CATEGORY_IS_REALNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameEqualTo(String value) {
            addCriterion("CATEGORY_IS_REALNAME =", value, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameNotEqualTo(String value) {
            addCriterion("CATEGORY_IS_REALNAME <>", value, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameGreaterThan(String value) {
            addCriterion("CATEGORY_IS_REALNAME >", value, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_IS_REALNAME >=", value, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameLessThan(String value) {
            addCriterion("CATEGORY_IS_REALNAME <", value, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_IS_REALNAME <=", value, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameLike(String value) {
            addCriterion("CATEGORY_IS_REALNAME like", value, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameNotLike(String value) {
            addCriterion("CATEGORY_IS_REALNAME not like", value, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameIn(List<String> values) {
            addCriterion("CATEGORY_IS_REALNAME in", values, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameNotIn(List<String> values) {
            addCriterion("CATEGORY_IS_REALNAME not in", values, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameBetween(String value1, String value2) {
            addCriterion("CATEGORY_IS_REALNAME between", value1, value2, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryIsRealnameNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_IS_REALNAME not between", value1, value2, "categoryIsRealname");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishIsNull() {
            addCriterion("CATEGORY_PUBLISH is null");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishIsNotNull() {
            addCriterion("CATEGORY_PUBLISH is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishEqualTo(String value) {
            addCriterion("CATEGORY_PUBLISH =", value, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishNotEqualTo(String value) {
            addCriterion("CATEGORY_PUBLISH <>", value, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishGreaterThan(String value) {
            addCriterion("CATEGORY_PUBLISH >", value, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_PUBLISH >=", value, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishLessThan(String value) {
            addCriterion("CATEGORY_PUBLISH <", value, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_PUBLISH <=", value, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishLike(String value) {
            addCriterion("CATEGORY_PUBLISH like", value, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishNotLike(String value) {
            addCriterion("CATEGORY_PUBLISH not like", value, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishIn(List<String> values) {
            addCriterion("CATEGORY_PUBLISH in", values, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishNotIn(List<String> values) {
            addCriterion("CATEGORY_PUBLISH not in", values, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishBetween(String value1, String value2) {
            addCriterion("CATEGORY_PUBLISH between", value1, value2, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryPublishNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_PUBLISH not between", value1, value2, "categoryPublish");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelIsNull() {
            addCriterion("CATEGORY_USE_CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelIsNotNull() {
            addCriterion("CATEGORY_USE_CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelEqualTo(String value) {
            addCriterion("CATEGORY_USE_CHANNEL =", value, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelNotEqualTo(String value) {
            addCriterion("CATEGORY_USE_CHANNEL <>", value, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelGreaterThan(String value) {
            addCriterion("CATEGORY_USE_CHANNEL >", value, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_USE_CHANNEL >=", value, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelLessThan(String value) {
            addCriterion("CATEGORY_USE_CHANNEL <", value, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_USE_CHANNEL <=", value, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelLike(String value) {
            addCriterion("CATEGORY_USE_CHANNEL like", value, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelNotLike(String value) {
            addCriterion("CATEGORY_USE_CHANNEL not like", value, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelIn(List<String> values) {
            addCriterion("CATEGORY_USE_CHANNEL in", values, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelNotIn(List<String> values) {
            addCriterion("CATEGORY_USE_CHANNEL not in", values, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelBetween(String value1, String value2) {
            addCriterion("CATEGORY_USE_CHANNEL between", value1, value2, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andCategoryUseChannelNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_USE_CHANNEL not between", value1, value2, "categoryUseChannel");
            return (Criteria) this;
        }

        public Criteria andMerchantNoIsNull() {
            addCriterion("MERCHANT_NO is null");
            return (Criteria) this;
        }

        public Criteria andMerchantNoIsNotNull() {
            addCriterion("MERCHANT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantNoEqualTo(String value) {
            addCriterion("MERCHANT_NO =", value, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoNotEqualTo(String value) {
            addCriterion("MERCHANT_NO <>", value, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoGreaterThan(String value) {
            addCriterion("MERCHANT_NO >", value, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoGreaterThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NO >=", value, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoLessThan(String value) {
            addCriterion("MERCHANT_NO <", value, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoLessThanOrEqualTo(String value) {
            addCriterion("MERCHANT_NO <=", value, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoLike(String value) {
            addCriterion("MERCHANT_NO like", value, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoNotLike(String value) {
            addCriterion("MERCHANT_NO not like", value, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoIn(List<String> values) {
            addCriterion("MERCHANT_NO in", values, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoNotIn(List<String> values) {
            addCriterion("MERCHANT_NO not in", values, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoBetween(String value1, String value2) {
            addCriterion("MERCHANT_NO between", value1, value2, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andMerchantNoNotBetween(String value1, String value2) {
            addCriterion("MERCHANT_NO not between", value1, value2, "merchantNo");
            return (Criteria) this;
        }

        public Criteria andCardProductIdIsNull() {
            addCriterion("CARD_PRODUCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCardProductIdIsNotNull() {
            addCriterion("CARD_PRODUCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCardProductIdEqualTo(String value) {
            addCriterion("CARD_PRODUCT_ID =", value, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdNotEqualTo(String value) {
            addCriterion("CARD_PRODUCT_ID <>", value, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdGreaterThan(String value) {
            addCriterion("CARD_PRODUCT_ID >", value, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_PRODUCT_ID >=", value, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdLessThan(String value) {
            addCriterion("CARD_PRODUCT_ID <", value, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdLessThanOrEqualTo(String value) {
            addCriterion("CARD_PRODUCT_ID <=", value, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdLike(String value) {
            addCriterion("CARD_PRODUCT_ID like", value, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdNotLike(String value) {
            addCriterion("CARD_PRODUCT_ID not like", value, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdIn(List<String> values) {
            addCriterion("CARD_PRODUCT_ID in", values, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdNotIn(List<String> values) {
            addCriterion("CARD_PRODUCT_ID not in", values, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdBetween(String value1, String value2) {
            addCriterion("CARD_PRODUCT_ID between", value1, value2, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andCardProductIdNotBetween(String value1, String value2) {
            addCriterion("CARD_PRODUCT_ID not between", value1, value2, "cardProductId");
            return (Criteria) this;
        }

        public Criteria andSettleTypeIsNull() {
            addCriterion("SETTLE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSettleTypeIsNotNull() {
            addCriterion("SETTLE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSettleTypeEqualTo(String value) {
            addCriterion("SETTLE_TYPE =", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeNotEqualTo(String value) {
            addCriterion("SETTLE_TYPE <>", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeGreaterThan(String value) {
            addCriterion("SETTLE_TYPE >", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SETTLE_TYPE >=", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeLessThan(String value) {
            addCriterion("SETTLE_TYPE <", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeLessThanOrEqualTo(String value) {
            addCriterion("SETTLE_TYPE <=", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeLike(String value) {
            addCriterion("SETTLE_TYPE like", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeNotLike(String value) {
            addCriterion("SETTLE_TYPE not like", value, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeIn(List<String> values) {
            addCriterion("SETTLE_TYPE in", values, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeNotIn(List<String> values) {
            addCriterion("SETTLE_TYPE not in", values, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeBetween(String value1, String value2) {
            addCriterion("SETTLE_TYPE between", value1, value2, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettleTypeNotBetween(String value1, String value2) {
            addCriterion("SETTLE_TYPE not between", value1, value2, "settleType");
            return (Criteria) this;
        }

        public Criteria andSettlePriceIsNull() {
            addCriterion("SETTLE_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andSettlePriceIsNotNull() {
            addCriterion("SETTLE_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSettlePriceEqualTo(Long value) {
            addCriterion("SETTLE_PRICE =", value, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andSettlePriceNotEqualTo(Long value) {
            addCriterion("SETTLE_PRICE <>", value, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andSettlePriceGreaterThan(Long value) {
            addCriterion("SETTLE_PRICE >", value, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andSettlePriceGreaterThanOrEqualTo(Long value) {
            addCriterion("SETTLE_PRICE >=", value, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andSettlePriceLessThan(Long value) {
            addCriterion("SETTLE_PRICE <", value, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andSettlePriceLessThanOrEqualTo(Long value) {
            addCriterion("SETTLE_PRICE <=", value, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andSettlePriceIn(List<Long> values) {
            addCriterion("SETTLE_PRICE in", values, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andSettlePriceNotIn(List<Long> values) {
            addCriterion("SETTLE_PRICE not in", values, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andSettlePriceBetween(Long value1, Long value2) {
            addCriterion("SETTLE_PRICE between", value1, value2, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andSettlePriceNotBetween(Long value1, Long value2) {
            addCriterion("SETTLE_PRICE not between", value1, value2, "settlePrice");
            return (Criteria) this;
        }

        public Criteria andIsFlySendIsNull() {
            addCriterion("IS_FLY_SEND is null");
            return (Criteria) this;
        }

        public Criteria andIsFlySendIsNotNull() {
            addCriterion("IS_FLY_SEND is not null");
            return (Criteria) this;
        }

        public Criteria andIsFlySendEqualTo(String value) {
            addCriterion("IS_FLY_SEND =", value, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendNotEqualTo(String value) {
            addCriterion("IS_FLY_SEND <>", value, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendGreaterThan(String value) {
            addCriterion("IS_FLY_SEND >", value, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendGreaterThanOrEqualTo(String value) {
            addCriterion("IS_FLY_SEND >=", value, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendLessThan(String value) {
            addCriterion("IS_FLY_SEND <", value, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendLessThanOrEqualTo(String value) {
            addCriterion("IS_FLY_SEND <=", value, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendLike(String value) {
            addCriterion("IS_FLY_SEND like", value, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendNotLike(String value) {
            addCriterion("IS_FLY_SEND not like", value, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendIn(List<String> values) {
            addCriterion("IS_FLY_SEND in", values, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendNotIn(List<String> values) {
            addCriterion("IS_FLY_SEND not in", values, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendBetween(String value1, String value2) {
            addCriterion("IS_FLY_SEND between", value1, value2, "isFlySend");
            return (Criteria) this;
        }

        public Criteria andIsFlySendNotBetween(String value1, String value2) {
            addCriterion("IS_FLY_SEND not between", value1, value2, "isFlySend");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table M_CARD_CATEGORY
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}