package com.cul.culsite.dto;

import java.util.Date;

public class MCloudIssuerSubjectInfoDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.GUID
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_DATE
     *
     * @mbggenerated
     */
    private String applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_TIME
     *
     * @mbggenerated
     */
    private String applyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_MAN
     *
     * @mbggenerated
     */
    private String applyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_NAME
     *
     * @mbggenerated
     */
    private String issuerSubjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_SHORT_NAME
     *
     * @mbggenerated
     */
    private String issuerSubjectShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_AUDI_STATUS
     *
     * @mbggenerated
     */
    private String issuerSubjectAudiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_STATUS
     *
     * @mbggenerated
     */
    private String issuerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_NO
     *
     * @mbggenerated
     */
    private String businessLicenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_PIC_URL
     *
     * @mbggenerated
     */
    private String businessLicensePicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_PIC_URL
     *
     * @mbggenerated
     */
    private String idCardPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ALIPAY_ACCOUNT_NO
     *
     * @mbggenerated
     */
    private String alipayAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_URL
     *
     * @mbggenerated
     */
    private String wechatUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID
     *
     * @mbggenerated
     */
    private String issuerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUBJECT_COMMENT
     *
     * @mbggenerated
     */
    private String subjectComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_MAN
     *
     * @mbggenerated
     */
    private String auditIssuerMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_DATE
     *
     * @mbggenerated
     */
    private Date auditIssuerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_CODE
     *
     * @mbggenerated
     */
    private String culCorpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_ADDRESS
     *
     * @mbggenerated
     */
    private String issuerSubjectAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_NO
     *
     * @mbggenerated
     */
    private String culCorpNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_LOGO_PIC
     *
     * @mbggenerated
     */
    private String issuerLogoPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.STOCK_LIMIT
     *
     * @mbggenerated
     */
    private Long stockLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VOUCHER_NUM_LIMIT
     *
     * @mbggenerated
     */
    private Long voucherNumLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISPAY
     *
     * @mbggenerated
     */
    private String ispay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_NUM
     *
     * @mbggenerated
     */
    private String merNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.EXPIRY_DAY
     *
     * @mbggenerated
     */
    private String expiryDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PAY_AMOUNT
     *
     * @mbggenerated
     */
    private Long payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_BACK_PIC_URL
     *
     * @mbggenerated
     */
    private String idCardBackPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID_QRCODE_URL
     *
     * @mbggenerated
     */
    private String issuerIdQrcodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_IDENTIFY
     *
     * @mbggenerated
     */
    private String wechatIdentify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ATTRIBUTETO
     *
     * @mbggenerated
     */
    private String attributeto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUPPORT_PAY_WAY
     *
     * @mbggenerated
     */
    private String supportPayWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_ISSUER_NO
     *
     * @mbggenerated
     */
    private String channelIssuerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_CARD
     *
     * @mbggenerated
     */
    private String isApplyCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_VOUCHER
     *
     * @mbggenerated
     */
    private String isApplyVoucher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.FUNC_VERSION
     *
     * @mbggenerated
     */
    private String funcVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CALL_BACK_STATUS
     *
     * @mbggenerated
     */
    private String callBackStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.INDS_CODE
     *
     * @mbggenerated
     */
    private String indsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ACCOUNT_SYSTEM
     *
     * @mbggenerated
     */
    private String accountSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_MSCORP
     *
     * @mbggenerated
     */
    private String isMscorp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_UNIQUENO
     *
     * @mbggenerated
     */
    private String issuerUniqueno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_PRIVATEKEY
     *
     * @mbggenerated
     */
    private String issuerPrivatekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_PIC_URL
     *
     * @mbggenerated
     */
    private String merPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_EXTENSION_NO
     *
     * @mbggenerated
     */
    private String channelExtensionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_START
     *
     * @mbggenerated
     */
    private Date validStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_END
     *
     * @mbggenerated
     */
    private Date validEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PRODUCT_ID
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_MER_TYPE
     *
     * @mbggenerated
     */
    private String businessMerType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.GUID
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.GUID
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.GUID
     *
     * @param guid the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.GUID
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_DATE
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_DATE
     *
     * @mbggenerated
     */
    public String getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_DATE
     *
     * @param applyDate the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_DATE
     *
     * @mbggenerated
     */
    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate == null ? null : applyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_TIME
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_TIME
     *
     * @mbggenerated
     */
    public String getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_TIME
     *
     * @param applyTime the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_TIME
     *
     * @mbggenerated
     */
    public void setApplyTime(String applyTime) {
        this.applyTime = applyTime == null ? null : applyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_MAN
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_MAN
     *
     * @mbggenerated
     */
    public String getApplyMan() {
        return applyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_MAN
     *
     * @param applyMan the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.APPLY_MAN
     *
     * @mbggenerated
     */
    public void setApplyMan(String applyMan) {
        this.applyMan = applyMan == null ? null : applyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_NAME
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_NAME
     *
     * @mbggenerated
     */
    public String getIssuerSubjectName() {
        return issuerSubjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_NAME
     *
     * @param issuerSubjectName the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_NAME
     *
     * @mbggenerated
     */
    public void setIssuerSubjectName(String issuerSubjectName) {
        this.issuerSubjectName = issuerSubjectName == null ? null : issuerSubjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_SHORT_NAME
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_SHORT_NAME
     *
     * @mbggenerated
     */
    public String getIssuerSubjectShortName() {
        return issuerSubjectShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_SHORT_NAME
     *
     * @param issuerSubjectShortName the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_SHORT_NAME
     *
     * @mbggenerated
     */
    public void setIssuerSubjectShortName(String issuerSubjectShortName) {
        this.issuerSubjectShortName = issuerSubjectShortName == null ? null : issuerSubjectShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_AUDI_STATUS
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_AUDI_STATUS
     *
     * @mbggenerated
     */
    public String getIssuerSubjectAudiStatus() {
        return issuerSubjectAudiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_AUDI_STATUS
     *
     * @param issuerSubjectAudiStatus the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_AUDI_STATUS
     *
     * @mbggenerated
     */
    public void setIssuerSubjectAudiStatus(String issuerSubjectAudiStatus) {
        this.issuerSubjectAudiStatus = issuerSubjectAudiStatus == null ? null : issuerSubjectAudiStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_STATUS
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_STATUS
     *
     * @mbggenerated
     */
    public String getIssuerStatus() {
        return issuerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_STATUS
     *
     * @param issuerStatus the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_STATUS
     *
     * @mbggenerated
     */
    public void setIssuerStatus(String issuerStatus) {
        this.issuerStatus = issuerStatus == null ? null : issuerStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_NO
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_NO
     *
     * @mbggenerated
     */
    public String getBusinessLicenseNo() {
        return businessLicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_NO
     *
     * @param businessLicenseNo the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_NO
     *
     * @mbggenerated
     */
    public void setBusinessLicenseNo(String businessLicenseNo) {
        this.businessLicenseNo = businessLicenseNo == null ? null : businessLicenseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_PIC_URL
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_PIC_URL
     *
     * @mbggenerated
     */
    public String getBusinessLicensePicUrl() {
        return businessLicensePicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_PIC_URL
     *
     * @param businessLicensePicUrl the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_LICENSE_PIC_URL
     *
     * @mbggenerated
     */
    public void setBusinessLicensePicUrl(String businessLicensePicUrl) {
        this.businessLicensePicUrl = businessLicensePicUrl == null ? null : businessLicensePicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_PIC_URL
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_PIC_URL
     *
     * @mbggenerated
     */
    public String getIdCardPicUrl() {
        return idCardPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_PIC_URL
     *
     * @param idCardPicUrl the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_PIC_URL
     *
     * @mbggenerated
     */
    public void setIdCardPicUrl(String idCardPicUrl) {
        this.idCardPicUrl = idCardPicUrl == null ? null : idCardPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ALIPAY_ACCOUNT_NO
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ALIPAY_ACCOUNT_NO
     *
     * @mbggenerated
     */
    public String getAlipayAccountNo() {
        return alipayAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ALIPAY_ACCOUNT_NO
     *
     * @param alipayAccountNo the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ALIPAY_ACCOUNT_NO
     *
     * @mbggenerated
     */
    public void setAlipayAccountNo(String alipayAccountNo) {
        this.alipayAccountNo = alipayAccountNo == null ? null : alipayAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_URL
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_URL
     *
     * @mbggenerated
     */
    public String getWechatUrl() {
        return wechatUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_URL
     *
     * @param wechatUrl the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_URL
     *
     * @mbggenerated
     */
    public void setWechatUrl(String wechatUrl) {
        this.wechatUrl = wechatUrl == null ? null : wechatUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID
     *
     * @mbggenerated
     */
    public String getIssuerId() {
        return issuerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID
     *
     * @param issuerId the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID
     *
     * @mbggenerated
     */
    public void setIssuerId(String issuerId) {
        this.issuerId = issuerId == null ? null : issuerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUBJECT_COMMENT
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUBJECT_COMMENT
     *
     * @mbggenerated
     */
    public String getSubjectComment() {
        return subjectComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUBJECT_COMMENT
     *
     * @param subjectComment the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUBJECT_COMMENT
     *
     * @mbggenerated
     */
    public void setSubjectComment(String subjectComment) {
        this.subjectComment = subjectComment == null ? null : subjectComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_MAN
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_MAN
     *
     * @mbggenerated
     */
    public String getAuditIssuerMan() {
        return auditIssuerMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_MAN
     *
     * @param auditIssuerMan the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_MAN
     *
     * @mbggenerated
     */
    public void setAuditIssuerMan(String auditIssuerMan) {
        this.auditIssuerMan = auditIssuerMan == null ? null : auditIssuerMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_DATE
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_DATE
     *
     * @mbggenerated
     */
    public Date getAuditIssuerDate() {
        return auditIssuerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_DATE
     *
     * @param auditIssuerDate the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.AUDIT_ISSUER_DATE
     *
     * @mbggenerated
     */
    public void setAuditIssuerDate(Date auditIssuerDate) {
        this.auditIssuerDate = auditIssuerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_USER
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_USER
     *
     * @param createUser the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_TIMESTAMP
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_USER
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_USER
     *
     * @param updateUser the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_TIMESTAMP
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL
     *
     * @param channel the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_CODE
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_CODE
     *
     * @mbggenerated
     */
    public String getCulCorpCode() {
        return culCorpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_CODE
     *
     * @param culCorpCode the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_CODE
     *
     * @mbggenerated
     */
    public void setCulCorpCode(String culCorpCode) {
        this.culCorpCode = culCorpCode == null ? null : culCorpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_ADDRESS
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_ADDRESS
     *
     * @mbggenerated
     */
    public String getIssuerSubjectAddress() {
        return issuerSubjectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_ADDRESS
     *
     * @param issuerSubjectAddress the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_SUBJECT_ADDRESS
     *
     * @mbggenerated
     */
    public void setIssuerSubjectAddress(String issuerSubjectAddress) {
        this.issuerSubjectAddress = issuerSubjectAddress == null ? null : issuerSubjectAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_NO
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_NO
     *
     * @mbggenerated
     */
    public String getCulCorpNo() {
        return culCorpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_NO
     *
     * @param culCorpNo the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CUL_CORP_NO
     *
     * @mbggenerated
     */
    public void setCulCorpNo(String culCorpNo) {
        this.culCorpNo = culCorpNo == null ? null : culCorpNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_LOGO_PIC
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_LOGO_PIC
     *
     * @mbggenerated
     */
    public String getIssuerLogoPic() {
        return issuerLogoPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_LOGO_PIC
     *
     * @param issuerLogoPic the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_LOGO_PIC
     *
     * @mbggenerated
     */
    public void setIssuerLogoPic(String issuerLogoPic) {
        this.issuerLogoPic = issuerLogoPic == null ? null : issuerLogoPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.STOCK_LIMIT
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.STOCK_LIMIT
     *
     * @mbggenerated
     */
    public Long getStockLimit() {
        return stockLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.STOCK_LIMIT
     *
     * @param stockLimit the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.STOCK_LIMIT
     *
     * @mbggenerated
     */
    public void setStockLimit(Long stockLimit) {
        this.stockLimit = stockLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VOUCHER_NUM_LIMIT
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VOUCHER_NUM_LIMIT
     *
     * @mbggenerated
     */
    public Long getVoucherNumLimit() {
        return voucherNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VOUCHER_NUM_LIMIT
     *
     * @param voucherNumLimit the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VOUCHER_NUM_LIMIT
     *
     * @mbggenerated
     */
    public void setVoucherNumLimit(Long voucherNumLimit) {
        this.voucherNumLimit = voucherNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISPAY
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISPAY
     *
     * @mbggenerated
     */
    public String getIspay() {
        return ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISPAY
     *
     * @param ispay the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISPAY
     *
     * @mbggenerated
     */
    public void setIspay(String ispay) {
        this.ispay = ispay == null ? null : ispay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_NUM
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_NUM
     *
     * @mbggenerated
     */
    public String getMerNum() {
        return merNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_NUM
     *
     * @param merNum the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_NUM
     *
     * @mbggenerated
     */
    public void setMerNum(String merNum) {
        this.merNum = merNum == null ? null : merNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.EXPIRY_DAY
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.EXPIRY_DAY
     *
     * @mbggenerated
     */
    public String getExpiryDay() {
        return expiryDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.EXPIRY_DAY
     *
     * @param expiryDay the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.EXPIRY_DAY
     *
     * @mbggenerated
     */
    public void setExpiryDay(String expiryDay) {
        this.expiryDay = expiryDay == null ? null : expiryDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PAY_AMOUNT
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PAY_AMOUNT
     *
     * @mbggenerated
     */
    public Long getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PAY_AMOUNT
     *
     * @param payAmount the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PAY_AMOUNT
     *
     * @mbggenerated
     */
    public void setPayAmount(Long payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_BACK_PIC_URL
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_BACK_PIC_URL
     *
     * @mbggenerated
     */
    public String getIdCardBackPicUrl() {
        return idCardBackPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_BACK_PIC_URL
     *
     * @param idCardBackPicUrl the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ID_CARD_BACK_PIC_URL
     *
     * @mbggenerated
     */
    public void setIdCardBackPicUrl(String idCardBackPicUrl) {
        this.idCardBackPicUrl = idCardBackPicUrl == null ? null : idCardBackPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID_QRCODE_URL
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID_QRCODE_URL
     *
     * @mbggenerated
     */
    public String getIssuerIdQrcodeUrl() {
        return issuerIdQrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID_QRCODE_URL
     *
     * @param issuerIdQrcodeUrl the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_ID_QRCODE_URL
     *
     * @mbggenerated
     */
    public void setIssuerIdQrcodeUrl(String issuerIdQrcodeUrl) {
        this.issuerIdQrcodeUrl = issuerIdQrcodeUrl == null ? null : issuerIdQrcodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_IDENTIFY
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_IDENTIFY
     *
     * @mbggenerated
     */
    public String getWechatIdentify() {
        return wechatIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_IDENTIFY
     *
     * @param wechatIdentify the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.WECHAT_IDENTIFY
     *
     * @mbggenerated
     */
    public void setWechatIdentify(String wechatIdentify) {
        this.wechatIdentify = wechatIdentify == null ? null : wechatIdentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ATTRIBUTETO
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ATTRIBUTETO
     *
     * @mbggenerated
     */
    public String getAttributeto() {
        return attributeto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ATTRIBUTETO
     *
     * @param attributeto the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ATTRIBUTETO
     *
     * @mbggenerated
     */
    public void setAttributeto(String attributeto) {
        this.attributeto = attributeto == null ? null : attributeto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUPPORT_PAY_WAY
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUPPORT_PAY_WAY
     *
     * @mbggenerated
     */
    public String getSupportPayWay() {
        return supportPayWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUPPORT_PAY_WAY
     *
     * @param supportPayWay the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.SUPPORT_PAY_WAY
     *
     * @mbggenerated
     */
    public void setSupportPayWay(String supportPayWay) {
        this.supportPayWay = supportPayWay == null ? null : supportPayWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_ISSUER_NO
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_ISSUER_NO
     *
     * @mbggenerated
     */
    public String getChannelIssuerNo() {
        return channelIssuerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_ISSUER_NO
     *
     * @param channelIssuerNo the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_ISSUER_NO
     *
     * @mbggenerated
     */
    public void setChannelIssuerNo(String channelIssuerNo) {
        this.channelIssuerNo = channelIssuerNo == null ? null : channelIssuerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_CARD
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_CARD
     *
     * @mbggenerated
     */
    public String getIsApplyCard() {
        return isApplyCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_CARD
     *
     * @param isApplyCard the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_CARD
     *
     * @mbggenerated
     */
    public void setIsApplyCard(String isApplyCard) {
        this.isApplyCard = isApplyCard == null ? null : isApplyCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_VOUCHER
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_VOUCHER
     *
     * @mbggenerated
     */
    public String getIsApplyVoucher() {
        return isApplyVoucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_VOUCHER
     *
     * @param isApplyVoucher the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_APPLY_VOUCHER
     *
     * @mbggenerated
     */
    public void setIsApplyVoucher(String isApplyVoucher) {
        this.isApplyVoucher = isApplyVoucher == null ? null : isApplyVoucher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.FUNC_VERSION
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.FUNC_VERSION
     *
     * @mbggenerated
     */
    public String getFuncVersion() {
        return funcVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.FUNC_VERSION
     *
     * @param funcVersion the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.FUNC_VERSION
     *
     * @mbggenerated
     */
    public void setFuncVersion(String funcVersion) {
        this.funcVersion = funcVersion == null ? null : funcVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CALL_BACK_STATUS
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CALL_BACK_STATUS
     *
     * @mbggenerated
     */
    public String getCallBackStatus() {
        return callBackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CALL_BACK_STATUS
     *
     * @param callBackStatus the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CALL_BACK_STATUS
     *
     * @mbggenerated
     */
    public void setCallBackStatus(String callBackStatus) {
        this.callBackStatus = callBackStatus == null ? null : callBackStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.INDS_CODE
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.INDS_CODE
     *
     * @mbggenerated
     */
    public String getIndsCode() {
        return indsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.INDS_CODE
     *
     * @param indsCode the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.INDS_CODE
     *
     * @mbggenerated
     */
    public void setIndsCode(String indsCode) {
        this.indsCode = indsCode == null ? null : indsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ACCOUNT_SYSTEM
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ACCOUNT_SYSTEM
     *
     * @mbggenerated
     */
    public String getAccountSystem() {
        return accountSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ACCOUNT_SYSTEM
     *
     * @param accountSystem the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ACCOUNT_SYSTEM
     *
     * @mbggenerated
     */
    public void setAccountSystem(String accountSystem) {
        this.accountSystem = accountSystem == null ? null : accountSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_MSCORP
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_MSCORP
     *
     * @mbggenerated
     */
    public String getIsMscorp() {
        return isMscorp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_MSCORP
     *
     * @param isMscorp the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.IS_MSCORP
     *
     * @mbggenerated
     */
    public void setIsMscorp(String isMscorp) {
        this.isMscorp = isMscorp == null ? null : isMscorp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.DESCRIPTION
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.DESCRIPTION
     *
     * @param description the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_UNIQUENO
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_UNIQUENO
     *
     * @mbggenerated
     */
    public String getIssuerUniqueno() {
        return issuerUniqueno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_UNIQUENO
     *
     * @param issuerUniqueno the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_UNIQUENO
     *
     * @mbggenerated
     */
    public void setIssuerUniqueno(String issuerUniqueno) {
        this.issuerUniqueno = issuerUniqueno == null ? null : issuerUniqueno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_PRIVATEKEY
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_PRIVATEKEY
     *
     * @mbggenerated
     */
    public String getIssuerPrivatekey() {
        return issuerPrivatekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_PRIVATEKEY
     *
     * @param issuerPrivatekey the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.ISSUER_PRIVATEKEY
     *
     * @mbggenerated
     */
    public void setIssuerPrivatekey(String issuerPrivatekey) {
        this.issuerPrivatekey = issuerPrivatekey == null ? null : issuerPrivatekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_PIC_URL
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_PIC_URL
     *
     * @mbggenerated
     */
    public String getMerPicUrl() {
        return merPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_PIC_URL
     *
     * @param merPicUrl the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.MER_PIC_URL
     *
     * @mbggenerated
     */
    public void setMerPicUrl(String merPicUrl) {
        this.merPicUrl = merPicUrl == null ? null : merPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_EXTENSION_NO
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_EXTENSION_NO
     *
     * @mbggenerated
     */
    public String getChannelExtensionNo() {
        return channelExtensionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_EXTENSION_NO
     *
     * @param channelExtensionNo the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.CHANNEL_EXTENSION_NO
     *
     * @mbggenerated
     */
    public void setChannelExtensionNo(String channelExtensionNo) {
        this.channelExtensionNo = channelExtensionNo == null ? null : channelExtensionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_START
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_START
     *
     * @mbggenerated
     */
    public Date getValidStart() {
        return validStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_START
     *
     * @param validStart the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_START
     *
     * @mbggenerated
     */
    public void setValidStart(Date validStart) {
        this.validStart = validStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_END
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_END
     *
     * @mbggenerated
     */
    public Date getValidEnd() {
        return validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_END
     *
     * @param validEnd the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.VALID_END
     *
     * @mbggenerated
     */
    public void setValidEnd(Date validEnd) {
        this.validEnd = validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PRODUCT_ID
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PRODUCT_ID
     *
     * @param productId the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_MER_TYPE
     *
     * @return the value of CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_MER_TYPE
     *
     * @mbggenerated
     */
    public String getBusinessMerType() {
        return businessMerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_MER_TYPE
     *
     * @param businessMerType the value for CULSITE.M_CLOUD_ISSUER_SUBJECT_INFO.BUSINESS_MER_TYPE
     *
     * @mbggenerated
     */
    public void setBusinessMerType(String businessMerType) {
        this.businessMerType = businessMerType == null ? null : businessMerType.trim();
    }
}