package com.cul.culsite.dto;

import java.util.Date;

public class MCustVoucherPurseDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.CUST_SEQ
     *
     * @mbggenerated
     */
    private String custSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.NO
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.VOUCHER_ID
     *
     * @mbggenerated
     */
    private String voucherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.USABLE_STATUS
     *
     * @mbggenerated
     */
    private String usableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_USER
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.VALID_START
     *
     * @mbggenerated
     */
    private Date validStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.VALID_END
     *
     * @mbggenerated
     */
    private Date validEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.TIMES
     *
     * @mbggenerated
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_CUST_VOUCHER_PURSE.M_VOUCHER_NO_ID
     *
     * @mbggenerated
     */
    private String mVoucherNoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.ID
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.ID
     *
     * @param id the value for CULSITE.M_CUST_VOUCHER_PURSE.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.CUST_SEQ
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.CUST_SEQ
     *
     * @mbggenerated
     */
    public String getCustSeq() {
        return custSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.CUST_SEQ
     *
     * @param custSeq the value for CULSITE.M_CUST_VOUCHER_PURSE.CUST_SEQ
     *
     * @mbggenerated
     */
    public void setCustSeq(String custSeq) {
        this.custSeq = custSeq == null ? null : custSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.TYPE
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.TYPE
     *
     * @param type the value for CULSITE.M_CUST_VOUCHER_PURSE.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.NO
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.NO
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.NO
     *
     * @param no the value for CULSITE.M_CUST_VOUCHER_PURSE.NO
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.VOUCHER_ID
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.VOUCHER_ID
     *
     * @mbggenerated
     */
    public String getVoucherId() {
        return voucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.VOUCHER_ID
     *
     * @param voucherId the value for CULSITE.M_CUST_VOUCHER_PURSE.VOUCHER_ID
     *
     * @mbggenerated
     */
    public void setVoucherId(String voucherId) {
        this.voucherId = voucherId == null ? null : voucherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.STATUS
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.STATUS
     *
     * @param status the value for CULSITE.M_CUST_VOUCHER_PURSE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.USABLE_STATUS
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.USABLE_STATUS
     *
     * @mbggenerated
     */
    public String getUsableStatus() {
        return usableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.USABLE_STATUS
     *
     * @param usableStatus the value for CULSITE.M_CUST_VOUCHER_PURSE.USABLE_STATUS
     *
     * @mbggenerated
     */
    public void setUsableStatus(String usableStatus) {
        this.usableStatus = usableStatus == null ? null : usableStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.REMARKS
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.REMARKS
     *
     * @param remarks the value for CULSITE.M_CUST_VOUCHER_PURSE.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.CREATE_USER
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.CREATE_USER
     *
     * @param createUser the value for CULSITE.M_CUST_VOUCHER_PURSE.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.CREATE_TIMESTAMP
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for CULSITE.M_CUST_VOUCHER_PURSE.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_USER
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_USER
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_USER
     *
     * @param updateUser the value for CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_USER
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_TIMESTAMP
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for CULSITE.M_CUST_VOUCHER_PURSE.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.VALID_START
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.VALID_START
     *
     * @mbggenerated
     */
    public Date getValidStart() {
        return validStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.VALID_START
     *
     * @param validStart the value for CULSITE.M_CUST_VOUCHER_PURSE.VALID_START
     *
     * @mbggenerated
     */
    public void setValidStart(Date validStart) {
        this.validStart = validStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.VALID_END
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.VALID_END
     *
     * @mbggenerated
     */
    public Date getValidEnd() {
        return validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.VALID_END
     *
     * @param validEnd the value for CULSITE.M_CUST_VOUCHER_PURSE.VALID_END
     *
     * @mbggenerated
     */
    public void setValidEnd(Date validEnd) {
        this.validEnd = validEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.TIMES
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.TIMES
     *
     * @mbggenerated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.TIMES
     *
     * @param times the value for CULSITE.M_CUST_VOUCHER_PURSE.TIMES
     *
     * @mbggenerated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.M_VOUCHER_NO_ID
     *
     * @return the value of CULSITE.M_CUST_VOUCHER_PURSE.M_VOUCHER_NO_ID
     *
     * @mbggenerated
     */
    public String getmVoucherNoId() {
        return mVoucherNoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_CUST_VOUCHER_PURSE.M_VOUCHER_NO_ID
     *
     * @param mVoucherNoId the value for CULSITE.M_CUST_VOUCHER_PURSE.M_VOUCHER_NO_ID
     *
     * @mbggenerated
     */
    public void setmVoucherNoId(String mVoucherNoId) {
        this.mVoucherNoId = mVoucherNoId == null ? null : mVoucherNoId.trim();
    }
}