package com.cul.culsite.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MGoodsCatDTOCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public MGoodsCatDTOCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMgcIdIsNull() {
            addCriterion("MGC_ID is null");
            return (Criteria) this;
        }

        public Criteria andMgcIdIsNotNull() {
            addCriterion("MGC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMgcIdEqualTo(String value) {
            addCriterion("MGC_ID =", value, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdNotEqualTo(String value) {
            addCriterion("MGC_ID <>", value, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdGreaterThan(String value) {
            addCriterion("MGC_ID >", value, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdGreaterThanOrEqualTo(String value) {
            addCriterion("MGC_ID >=", value, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdLessThan(String value) {
            addCriterion("MGC_ID <", value, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdLessThanOrEqualTo(String value) {
            addCriterion("MGC_ID <=", value, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdLike(String value) {
            addCriterion("MGC_ID like", value, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdNotLike(String value) {
            addCriterion("MGC_ID not like", value, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdIn(List<String> values) {
            addCriterion("MGC_ID in", values, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdNotIn(List<String> values) {
            addCriterion("MGC_ID not in", values, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdBetween(String value1, String value2) {
            addCriterion("MGC_ID between", value1, value2, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIdNotBetween(String value1, String value2) {
            addCriterion("MGC_ID not between", value1, value2, "mgcId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdIsNull() {
            addCriterion("MGC_ISSUER_ID is null");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdIsNotNull() {
            addCriterion("MGC_ISSUER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdEqualTo(String value) {
            addCriterion("MGC_ISSUER_ID =", value, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdNotEqualTo(String value) {
            addCriterion("MGC_ISSUER_ID <>", value, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdGreaterThan(String value) {
            addCriterion("MGC_ISSUER_ID >", value, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdGreaterThanOrEqualTo(String value) {
            addCriterion("MGC_ISSUER_ID >=", value, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdLessThan(String value) {
            addCriterion("MGC_ISSUER_ID <", value, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdLessThanOrEqualTo(String value) {
            addCriterion("MGC_ISSUER_ID <=", value, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdLike(String value) {
            addCriterion("MGC_ISSUER_ID like", value, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdNotLike(String value) {
            addCriterion("MGC_ISSUER_ID not like", value, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdIn(List<String> values) {
            addCriterion("MGC_ISSUER_ID in", values, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdNotIn(List<String> values) {
            addCriterion("MGC_ISSUER_ID not in", values, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdBetween(String value1, String value2) {
            addCriterion("MGC_ISSUER_ID between", value1, value2, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcIssuerIdNotBetween(String value1, String value2) {
            addCriterion("MGC_ISSUER_ID not between", value1, value2, "mgcIssuerId");
            return (Criteria) this;
        }

        public Criteria andMgcTypeIsNull() {
            addCriterion("MGC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMgcTypeIsNotNull() {
            addCriterion("MGC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMgcTypeEqualTo(String value) {
            addCriterion("MGC_TYPE =", value, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeNotEqualTo(String value) {
            addCriterion("MGC_TYPE <>", value, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeGreaterThan(String value) {
            addCriterion("MGC_TYPE >", value, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MGC_TYPE >=", value, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeLessThan(String value) {
            addCriterion("MGC_TYPE <", value, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeLessThanOrEqualTo(String value) {
            addCriterion("MGC_TYPE <=", value, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeLike(String value) {
            addCriterion("MGC_TYPE like", value, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeNotLike(String value) {
            addCriterion("MGC_TYPE not like", value, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeIn(List<String> values) {
            addCriterion("MGC_TYPE in", values, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeNotIn(List<String> values) {
            addCriterion("MGC_TYPE not in", values, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeBetween(String value1, String value2) {
            addCriterion("MGC_TYPE between", value1, value2, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcTypeNotBetween(String value1, String value2) {
            addCriterion("MGC_TYPE not between", value1, value2, "mgcType");
            return (Criteria) this;
        }

        public Criteria andMgcCodeIsNull() {
            addCriterion("MGC_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMgcCodeIsNotNull() {
            addCriterion("MGC_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMgcCodeEqualTo(String value) {
            addCriterion("MGC_CODE =", value, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeNotEqualTo(String value) {
            addCriterion("MGC_CODE <>", value, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeGreaterThan(String value) {
            addCriterion("MGC_CODE >", value, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeGreaterThanOrEqualTo(String value) {
            addCriterion("MGC_CODE >=", value, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeLessThan(String value) {
            addCriterion("MGC_CODE <", value, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeLessThanOrEqualTo(String value) {
            addCriterion("MGC_CODE <=", value, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeLike(String value) {
            addCriterion("MGC_CODE like", value, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeNotLike(String value) {
            addCriterion("MGC_CODE not like", value, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeIn(List<String> values) {
            addCriterion("MGC_CODE in", values, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeNotIn(List<String> values) {
            addCriterion("MGC_CODE not in", values, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeBetween(String value1, String value2) {
            addCriterion("MGC_CODE between", value1, value2, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcCodeNotBetween(String value1, String value2) {
            addCriterion("MGC_CODE not between", value1, value2, "mgcCode");
            return (Criteria) this;
        }

        public Criteria andMgcNameIsNull() {
            addCriterion("MGC_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMgcNameIsNotNull() {
            addCriterion("MGC_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMgcNameEqualTo(String value) {
            addCriterion("MGC_NAME =", value, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameNotEqualTo(String value) {
            addCriterion("MGC_NAME <>", value, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameGreaterThan(String value) {
            addCriterion("MGC_NAME >", value, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameGreaterThanOrEqualTo(String value) {
            addCriterion("MGC_NAME >=", value, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameLessThan(String value) {
            addCriterion("MGC_NAME <", value, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameLessThanOrEqualTo(String value) {
            addCriterion("MGC_NAME <=", value, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameLike(String value) {
            addCriterion("MGC_NAME like", value, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameNotLike(String value) {
            addCriterion("MGC_NAME not like", value, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameIn(List<String> values) {
            addCriterion("MGC_NAME in", values, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameNotIn(List<String> values) {
            addCriterion("MGC_NAME not in", values, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameBetween(String value1, String value2) {
            addCriterion("MGC_NAME between", value1, value2, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcNameNotBetween(String value1, String value2) {
            addCriterion("MGC_NAME not between", value1, value2, "mgcName");
            return (Criteria) this;
        }

        public Criteria andMgcUrlIsNull() {
            addCriterion("MGC_URL is null");
            return (Criteria) this;
        }

        public Criteria andMgcUrlIsNotNull() {
            addCriterion("MGC_URL is not null");
            return (Criteria) this;
        }

        public Criteria andMgcUrlEqualTo(String value) {
            addCriterion("MGC_URL =", value, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlNotEqualTo(String value) {
            addCriterion("MGC_URL <>", value, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlGreaterThan(String value) {
            addCriterion("MGC_URL >", value, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlGreaterThanOrEqualTo(String value) {
            addCriterion("MGC_URL >=", value, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlLessThan(String value) {
            addCriterion("MGC_URL <", value, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlLessThanOrEqualTo(String value) {
            addCriterion("MGC_URL <=", value, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlLike(String value) {
            addCriterion("MGC_URL like", value, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlNotLike(String value) {
            addCriterion("MGC_URL not like", value, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlIn(List<String> values) {
            addCriterion("MGC_URL in", values, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlNotIn(List<String> values) {
            addCriterion("MGC_URL not in", values, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlBetween(String value1, String value2) {
            addCriterion("MGC_URL between", value1, value2, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcUrlNotBetween(String value1, String value2) {
            addCriterion("MGC_URL not between", value1, value2, "mgcUrl");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoIsNull() {
            addCriterion("MGC_PARENT_NO is null");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoIsNotNull() {
            addCriterion("MGC_PARENT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoEqualTo(String value) {
            addCriterion("MGC_PARENT_NO =", value, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoNotEqualTo(String value) {
            addCriterion("MGC_PARENT_NO <>", value, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoGreaterThan(String value) {
            addCriterion("MGC_PARENT_NO >", value, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoGreaterThanOrEqualTo(String value) {
            addCriterion("MGC_PARENT_NO >=", value, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoLessThan(String value) {
            addCriterion("MGC_PARENT_NO <", value, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoLessThanOrEqualTo(String value) {
            addCriterion("MGC_PARENT_NO <=", value, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoLike(String value) {
            addCriterion("MGC_PARENT_NO like", value, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoNotLike(String value) {
            addCriterion("MGC_PARENT_NO not like", value, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoIn(List<String> values) {
            addCriterion("MGC_PARENT_NO in", values, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoNotIn(List<String> values) {
            addCriterion("MGC_PARENT_NO not in", values, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoBetween(String value1, String value2) {
            addCriterion("MGC_PARENT_NO between", value1, value2, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcParentNoNotBetween(String value1, String value2) {
            addCriterion("MGC_PARENT_NO not between", value1, value2, "mgcParentNo");
            return (Criteria) this;
        }

        public Criteria andMgcStatusIsNull() {
            addCriterion("MGC_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andMgcStatusIsNotNull() {
            addCriterion("MGC_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andMgcStatusEqualTo(String value) {
            addCriterion("MGC_STATUS =", value, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusNotEqualTo(String value) {
            addCriterion("MGC_STATUS <>", value, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusGreaterThan(String value) {
            addCriterion("MGC_STATUS >", value, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusGreaterThanOrEqualTo(String value) {
            addCriterion("MGC_STATUS >=", value, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusLessThan(String value) {
            addCriterion("MGC_STATUS <", value, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusLessThanOrEqualTo(String value) {
            addCriterion("MGC_STATUS <=", value, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusLike(String value) {
            addCriterion("MGC_STATUS like", value, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusNotLike(String value) {
            addCriterion("MGC_STATUS not like", value, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusIn(List<String> values) {
            addCriterion("MGC_STATUS in", values, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusNotIn(List<String> values) {
            addCriterion("MGC_STATUS not in", values, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusBetween(String value1, String value2) {
            addCriterion("MGC_STATUS between", value1, value2, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andMgcStatusNotBetween(String value1, String value2) {
            addCriterion("MGC_STATUS not between", value1, value2, "mgcStatus");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("CREATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("CREATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATE_TIMESTAMP not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishAreaIsNull() {
            addCriterion("PUBLISH_AREA is null");
            return (Criteria) this;
        }

        public Criteria andPublishAreaIsNotNull() {
            addCriterion("PUBLISH_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andPublishAreaEqualTo(String value) {
            addCriterion("PUBLISH_AREA =", value, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaNotEqualTo(String value) {
            addCriterion("PUBLISH_AREA <>", value, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaGreaterThan(String value) {
            addCriterion("PUBLISH_AREA >", value, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLISH_AREA >=", value, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaLessThan(String value) {
            addCriterion("PUBLISH_AREA <", value, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaLessThanOrEqualTo(String value) {
            addCriterion("PUBLISH_AREA <=", value, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaLike(String value) {
            addCriterion("PUBLISH_AREA like", value, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaNotLike(String value) {
            addCriterion("PUBLISH_AREA not like", value, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaIn(List<String> values) {
            addCriterion("PUBLISH_AREA in", values, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaNotIn(List<String> values) {
            addCriterion("PUBLISH_AREA not in", values, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaBetween(String value1, String value2) {
            addCriterion("PUBLISH_AREA between", value1, value2, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishAreaNotBetween(String value1, String value2) {
            addCriterion("PUBLISH_AREA not between", value1, value2, "publishArea");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerIsNull() {
            addCriterion("PUBLISH_ISSUER is null");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerIsNotNull() {
            addCriterion("PUBLISH_ISSUER is not null");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerEqualTo(String value) {
            addCriterion("PUBLISH_ISSUER =", value, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerNotEqualTo(String value) {
            addCriterion("PUBLISH_ISSUER <>", value, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerGreaterThan(String value) {
            addCriterion("PUBLISH_ISSUER >", value, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLISH_ISSUER >=", value, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerLessThan(String value) {
            addCriterion("PUBLISH_ISSUER <", value, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerLessThanOrEqualTo(String value) {
            addCriterion("PUBLISH_ISSUER <=", value, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerLike(String value) {
            addCriterion("PUBLISH_ISSUER like", value, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerNotLike(String value) {
            addCriterion("PUBLISH_ISSUER not like", value, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerIn(List<String> values) {
            addCriterion("PUBLISH_ISSUER in", values, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerNotIn(List<String> values) {
            addCriterion("PUBLISH_ISSUER not in", values, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerBetween(String value1, String value2) {
            addCriterion("PUBLISH_ISSUER between", value1, value2, "publishIssuer");
            return (Criteria) this;
        }

        public Criteria andPublishIssuerNotBetween(String value1, String value2) {
            addCriterion("PUBLISH_ISSUER not between", value1, value2, "publishIssuer");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CULSITE.M_GOODS_CAT
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}