package com.cul.culsite.dto;

import java.math.BigDecimal;
import java.util.Date;

public class MOrderTxnDetailDTO extends MOrderTxnDetailDTOKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_AMOUNT
     *
     * @mbggenerated
     */
    private Long motdAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_HOLDER_MOBILE
     *
     * @mbggenerated
     */
    private String motdHolderMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_FEE
     *
     * @mbggenerated
     */
    private BigDecimal motdCardFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PRODUCT_ID
     *
     * @mbggenerated
     */
    private String motdProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_LMS_TXN_ID
     *
     * @mbggenerated
     */
    private String motdLmsTxnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PAY_AMOUNT
     *
     * @mbggenerated
     */
    private Long motdPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_AMOUNT
     *
     * @mbggenerated
     */
    private Long motdPromotionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_DIR
     *
     * @mbggenerated
     */
    private String motdDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_ID
     *
     * @mbggenerated
     */
    private String motdPromotionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_TYPE
     *
     * @mbggenerated
     */
    private String motdCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_DETAIL_TXN_SEQ
     *
     * @mbggenerated
     */
    private Long motdDetailTxnSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_AMOUNT
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_AMOUNT
     *
     * @mbggenerated
     */
    public Long getMotdAmount() {
        return motdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_AMOUNT
     *
     * @param motdAmount the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_AMOUNT
     *
     * @mbggenerated
     */
    public void setMotdAmount(Long motdAmount) {
        this.motdAmount = motdAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_HOLDER_MOBILE
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_HOLDER_MOBILE
     *
     * @mbggenerated
     */
    public String getMotdHolderMobile() {
        return motdHolderMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_HOLDER_MOBILE
     *
     * @param motdHolderMobile the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_HOLDER_MOBILE
     *
     * @mbggenerated
     */
    public void setMotdHolderMobile(String motdHolderMobile) {
        this.motdHolderMobile = motdHolderMobile == null ? null : motdHolderMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.CREATE_TIME
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.CREATE_TIME
     *
     * @param createTime the value for CULSITE.M_ORDER_TXN_DETAIL.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_FEE
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_FEE
     *
     * @mbggenerated
     */
    public BigDecimal getMotdCardFee() {
        return motdCardFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_FEE
     *
     * @param motdCardFee the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_FEE
     *
     * @mbggenerated
     */
    public void setMotdCardFee(BigDecimal motdCardFee) {
        this.motdCardFee = motdCardFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PRODUCT_ID
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getMotdProductId() {
        return motdProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PRODUCT_ID
     *
     * @param motdProductId the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setMotdProductId(String motdProductId) {
        this.motdProductId = motdProductId == null ? null : motdProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_LMS_TXN_ID
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_LMS_TXN_ID
     *
     * @mbggenerated
     */
    public String getMotdLmsTxnId() {
        return motdLmsTxnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_LMS_TXN_ID
     *
     * @param motdLmsTxnId the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_LMS_TXN_ID
     *
     * @mbggenerated
     */
    public void setMotdLmsTxnId(String motdLmsTxnId) {
        this.motdLmsTxnId = motdLmsTxnId == null ? null : motdLmsTxnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PAY_AMOUNT
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_PAY_AMOUNT
     *
     * @mbggenerated
     */
    public Long getMotdPayAmount() {
        return motdPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PAY_AMOUNT
     *
     * @param motdPayAmount the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_PAY_AMOUNT
     *
     * @mbggenerated
     */
    public void setMotdPayAmount(Long motdPayAmount) {
        this.motdPayAmount = motdPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_AMOUNT
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_AMOUNT
     *
     * @mbggenerated
     */
    public Long getMotdPromotionAmount() {
        return motdPromotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_AMOUNT
     *
     * @param motdPromotionAmount the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_AMOUNT
     *
     * @mbggenerated
     */
    public void setMotdPromotionAmount(Long motdPromotionAmount) {
        this.motdPromotionAmount = motdPromotionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_DIR
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_DIR
     *
     * @mbggenerated
     */
    public String getMotdDir() {
        return motdDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_DIR
     *
     * @param motdDir the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_DIR
     *
     * @mbggenerated
     */
    public void setMotdDir(String motdDir) {
        this.motdDir = motdDir == null ? null : motdDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_ID
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_ID
     *
     * @mbggenerated
     */
    public String getMotdPromotionId() {
        return motdPromotionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_ID
     *
     * @param motdPromotionId the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_PROMOTION_ID
     *
     * @mbggenerated
     */
    public void setMotdPromotionId(String motdPromotionId) {
        this.motdPromotionId = motdPromotionId == null ? null : motdPromotionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_TYPE
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_TYPE
     *
     * @mbggenerated
     */
    public String getMotdCardType() {
        return motdCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_TYPE
     *
     * @param motdCardType the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_CARD_TYPE
     *
     * @mbggenerated
     */
    public void setMotdCardType(String motdCardType) {
        this.motdCardType = motdCardType == null ? null : motdCardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_DETAIL_TXN_SEQ
     *
     * @return the value of CULSITE.M_ORDER_TXN_DETAIL.MOTD_DETAIL_TXN_SEQ
     *
     * @mbggenerated
     */
    public Long getMotdDetailTxnSeq() {
        return motdDetailTxnSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_ORDER_TXN_DETAIL.MOTD_DETAIL_TXN_SEQ
     *
     * @param motdDetailTxnSeq the value for CULSITE.M_ORDER_TXN_DETAIL.MOTD_DETAIL_TXN_SEQ
     *
     * @mbggenerated
     */
    public void setMotdDetailTxnSeq(Long motdDetailTxnSeq) {
        this.motdDetailTxnSeq = motdDetailTxnSeq;
    }
}