package com.cul.culsite.dto;

import java.math.BigDecimal;

public class MProductSeq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_SEQ.MPS_ID
     *
     * @mbggenerated
     */
    private String mpsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_SEQ.MPS_QUERY_SEQ
     *
     * @mbggenerated
     */
    private BigDecimal mpsQuerySeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_SEQ.MPS_IMPORT_SEQ
     *
     * @mbggenerated
     */
    private BigDecimal mpsImportSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CULSITE.M_PRODUCT_SEQ.MPS_PRODUCT_ID
     *
     * @mbggenerated
     */
    private String mpsProductId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_SEQ.MPS_ID
     *
     * @return the value of CULSITE.M_PRODUCT_SEQ.MPS_ID
     *
     * @mbggenerated
     */
    public String getMpsId() {
        return mpsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_SEQ.MPS_ID
     *
     * @param mpsId the value for CULSITE.M_PRODUCT_SEQ.MPS_ID
     *
     * @mbggenerated
     */
    public void setMpsId(String mpsId) {
        this.mpsId = mpsId == null ? null : mpsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_SEQ.MPS_QUERY_SEQ
     *
     * @return the value of CULSITE.M_PRODUCT_SEQ.MPS_QUERY_SEQ
     *
     * @mbggenerated
     */
    public BigDecimal getMpsQuerySeq() {
        return mpsQuerySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_SEQ.MPS_QUERY_SEQ
     *
     * @param mpsQuerySeq the value for CULSITE.M_PRODUCT_SEQ.MPS_QUERY_SEQ
     *
     * @mbggenerated
     */
    public void setMpsQuerySeq(BigDecimal mpsQuerySeq) {
        this.mpsQuerySeq = mpsQuerySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_SEQ.MPS_IMPORT_SEQ
     *
     * @return the value of CULSITE.M_PRODUCT_SEQ.MPS_IMPORT_SEQ
     *
     * @mbggenerated
     */
    public BigDecimal getMpsImportSeq() {
        return mpsImportSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_SEQ.MPS_IMPORT_SEQ
     *
     * @param mpsImportSeq the value for CULSITE.M_PRODUCT_SEQ.MPS_IMPORT_SEQ
     *
     * @mbggenerated
     */
    public void setMpsImportSeq(BigDecimal mpsImportSeq) {
        this.mpsImportSeq = mpsImportSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CULSITE.M_PRODUCT_SEQ.MPS_PRODUCT_ID
     *
     * @return the value of CULSITE.M_PRODUCT_SEQ.MPS_PRODUCT_ID
     *
     * @mbggenerated
     */
    public String getMpsProductId() {
        return mpsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CULSITE.M_PRODUCT_SEQ.MPS_PRODUCT_ID
     *
     * @param mpsProductId the value for CULSITE.M_PRODUCT_SEQ.MPS_PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setMpsProductId(String mpsProductId) {
        this.mpsProductId = mpsProductId == null ? null : mpsProductId.trim();
    }
}