package com.cul.culsite.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MTransHeaderDTOCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public MTransHeaderDTOCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMthTransIdIsNull() {
            addCriterion("MTH_TRANS_ID is null");
            return (Criteria) this;
        }

        public Criteria andMthTransIdIsNotNull() {
            addCriterion("MTH_TRANS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMthTransIdEqualTo(String value) {
            addCriterion("MTH_TRANS_ID =", value, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdNotEqualTo(String value) {
            addCriterion("MTH_TRANS_ID <>", value, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdGreaterThan(String value) {
            addCriterion("MTH_TRANS_ID >", value, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_TRANS_ID >=", value, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdLessThan(String value) {
            addCriterion("MTH_TRANS_ID <", value, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdLessThanOrEqualTo(String value) {
            addCriterion("MTH_TRANS_ID <=", value, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdLike(String value) {
            addCriterion("MTH_TRANS_ID like", value, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdNotLike(String value) {
            addCriterion("MTH_TRANS_ID not like", value, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdIn(List<String> values) {
            addCriterion("MTH_TRANS_ID in", values, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdNotIn(List<String> values) {
            addCriterion("MTH_TRANS_ID not in", values, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdBetween(String value1, String value2) {
            addCriterion("MTH_TRANS_ID between", value1, value2, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthTransIdNotBetween(String value1, String value2) {
            addCriterion("MTH_TRANS_ID not between", value1, value2, "mthTransId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdIsNull() {
            addCriterion("MTH_ORG_TXN_ID is null");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdIsNotNull() {
            addCriterion("MTH_ORG_TXN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdEqualTo(String value) {
            addCriterion("MTH_ORG_TXN_ID =", value, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdNotEqualTo(String value) {
            addCriterion("MTH_ORG_TXN_ID <>", value, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdGreaterThan(String value) {
            addCriterion("MTH_ORG_TXN_ID >", value, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_ORG_TXN_ID >=", value, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdLessThan(String value) {
            addCriterion("MTH_ORG_TXN_ID <", value, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdLessThanOrEqualTo(String value) {
            addCriterion("MTH_ORG_TXN_ID <=", value, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdLike(String value) {
            addCriterion("MTH_ORG_TXN_ID like", value, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdNotLike(String value) {
            addCriterion("MTH_ORG_TXN_ID not like", value, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdIn(List<String> values) {
            addCriterion("MTH_ORG_TXN_ID in", values, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdNotIn(List<String> values) {
            addCriterion("MTH_ORG_TXN_ID not in", values, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdBetween(String value1, String value2) {
            addCriterion("MTH_ORG_TXN_ID between", value1, value2, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthOrgTxnIdNotBetween(String value1, String value2) {
            addCriterion("MTH_ORG_TXN_ID not between", value1, value2, "mthOrgTxnId");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoIsNull() {
            addCriterion("MTH_MERCHANT_NO is null");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoIsNotNull() {
            addCriterion("MTH_MERCHANT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoEqualTo(String value) {
            addCriterion("MTH_MERCHANT_NO =", value, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoNotEqualTo(String value) {
            addCriterion("MTH_MERCHANT_NO <>", value, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoGreaterThan(String value) {
            addCriterion("MTH_MERCHANT_NO >", value, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_MERCHANT_NO >=", value, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoLessThan(String value) {
            addCriterion("MTH_MERCHANT_NO <", value, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoLessThanOrEqualTo(String value) {
            addCriterion("MTH_MERCHANT_NO <=", value, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoLike(String value) {
            addCriterion("MTH_MERCHANT_NO like", value, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoNotLike(String value) {
            addCriterion("MTH_MERCHANT_NO not like", value, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoIn(List<String> values) {
            addCriterion("MTH_MERCHANT_NO in", values, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoNotIn(List<String> values) {
            addCriterion("MTH_MERCHANT_NO not in", values, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoBetween(String value1, String value2) {
            addCriterion("MTH_MERCHANT_NO between", value1, value2, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthMerchantNoNotBetween(String value1, String value2) {
            addCriterion("MTH_MERCHANT_NO not between", value1, value2, "mthMerchantNo");
            return (Criteria) this;
        }

        public Criteria andMthDtIsNull() {
            addCriterion("MTH_DT is null");
            return (Criteria) this;
        }

        public Criteria andMthDtIsNotNull() {
            addCriterion("MTH_DT is not null");
            return (Criteria) this;
        }

        public Criteria andMthDtEqualTo(String value) {
            addCriterion("MTH_DT =", value, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtNotEqualTo(String value) {
            addCriterion("MTH_DT <>", value, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtGreaterThan(String value) {
            addCriterion("MTH_DT >", value, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_DT >=", value, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtLessThan(String value) {
            addCriterion("MTH_DT <", value, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtLessThanOrEqualTo(String value) {
            addCriterion("MTH_DT <=", value, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtLike(String value) {
            addCriterion("MTH_DT like", value, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtNotLike(String value) {
            addCriterion("MTH_DT not like", value, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtIn(List<String> values) {
            addCriterion("MTH_DT in", values, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtNotIn(List<String> values) {
            addCriterion("MTH_DT not in", values, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtBetween(String value1, String value2) {
            addCriterion("MTH_DT between", value1, value2, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthDtNotBetween(String value1, String value2) {
            addCriterion("MTH_DT not between", value1, value2, "mthDt");
            return (Criteria) this;
        }

        public Criteria andMthStanIsNull() {
            addCriterion("MTH_STAN is null");
            return (Criteria) this;
        }

        public Criteria andMthStanIsNotNull() {
            addCriterion("MTH_STAN is not null");
            return (Criteria) this;
        }

        public Criteria andMthStanEqualTo(String value) {
            addCriterion("MTH_STAN =", value, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanNotEqualTo(String value) {
            addCriterion("MTH_STAN <>", value, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanGreaterThan(String value) {
            addCriterion("MTH_STAN >", value, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_STAN >=", value, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanLessThan(String value) {
            addCriterion("MTH_STAN <", value, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanLessThanOrEqualTo(String value) {
            addCriterion("MTH_STAN <=", value, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanLike(String value) {
            addCriterion("MTH_STAN like", value, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanNotLike(String value) {
            addCriterion("MTH_STAN not like", value, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanIn(List<String> values) {
            addCriterion("MTH_STAN in", values, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanNotIn(List<String> values) {
            addCriterion("MTH_STAN not in", values, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanBetween(String value1, String value2) {
            addCriterion("MTH_STAN between", value1, value2, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStanNotBetween(String value1, String value2) {
            addCriterion("MTH_STAN not between", value1, value2, "mthStan");
            return (Criteria) this;
        }

        public Criteria andMthStatusIsNull() {
            addCriterion("MTH_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andMthStatusIsNotNull() {
            addCriterion("MTH_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andMthStatusEqualTo(String value) {
            addCriterion("MTH_STATUS =", value, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusNotEqualTo(String value) {
            addCriterion("MTH_STATUS <>", value, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusGreaterThan(String value) {
            addCriterion("MTH_STATUS >", value, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_STATUS >=", value, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusLessThan(String value) {
            addCriterion("MTH_STATUS <", value, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusLessThanOrEqualTo(String value) {
            addCriterion("MTH_STATUS <=", value, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusLike(String value) {
            addCriterion("MTH_STATUS like", value, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusNotLike(String value) {
            addCriterion("MTH_STATUS not like", value, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusIn(List<String> values) {
            addCriterion("MTH_STATUS in", values, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusNotIn(List<String> values) {
            addCriterion("MTH_STATUS not in", values, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusBetween(String value1, String value2) {
            addCriterion("MTH_STATUS between", value1, value2, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andMthStatusNotBetween(String value1, String value2) {
            addCriterion("MTH_STATUS not between", value1, value2, "mthStatus");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("CREATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("CREATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("CREATE_TIMESTAMP >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("CREATE_TIMESTAMP <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdIsNull() {
            addCriterion("MTH_SOURCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdIsNotNull() {
            addCriterion("MTH_SOURCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdEqualTo(String value) {
            addCriterion("MTH_SOURCE_ID =", value, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdNotEqualTo(String value) {
            addCriterion("MTH_SOURCE_ID <>", value, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdGreaterThan(String value) {
            addCriterion("MTH_SOURCE_ID >", value, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_SOURCE_ID >=", value, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdLessThan(String value) {
            addCriterion("MTH_SOURCE_ID <", value, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdLessThanOrEqualTo(String value) {
            addCriterion("MTH_SOURCE_ID <=", value, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdLike(String value) {
            addCriterion("MTH_SOURCE_ID like", value, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdNotLike(String value) {
            addCriterion("MTH_SOURCE_ID not like", value, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdIn(List<String> values) {
            addCriterion("MTH_SOURCE_ID in", values, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdNotIn(List<String> values) {
            addCriterion("MTH_SOURCE_ID not in", values, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdBetween(String value1, String value2) {
            addCriterion("MTH_SOURCE_ID between", value1, value2, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthSourceIdNotBetween(String value1, String value2) {
            addCriterion("MTH_SOURCE_ID not between", value1, value2, "mthSourceId");
            return (Criteria) this;
        }

        public Criteria andMthUseridIsNull() {
            addCriterion("MTH_USERID is null");
            return (Criteria) this;
        }

        public Criteria andMthUseridIsNotNull() {
            addCriterion("MTH_USERID is not null");
            return (Criteria) this;
        }

        public Criteria andMthUseridEqualTo(String value) {
            addCriterion("MTH_USERID =", value, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridNotEqualTo(String value) {
            addCriterion("MTH_USERID <>", value, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridGreaterThan(String value) {
            addCriterion("MTH_USERID >", value, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_USERID >=", value, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridLessThan(String value) {
            addCriterion("MTH_USERID <", value, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridLessThanOrEqualTo(String value) {
            addCriterion("MTH_USERID <=", value, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridLike(String value) {
            addCriterion("MTH_USERID like", value, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridNotLike(String value) {
            addCriterion("MTH_USERID not like", value, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridIn(List<String> values) {
            addCriterion("MTH_USERID in", values, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridNotIn(List<String> values) {
            addCriterion("MTH_USERID not in", values, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridBetween(String value1, String value2) {
            addCriterion("MTH_USERID between", value1, value2, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthUseridNotBetween(String value1, String value2) {
            addCriterion("MTH_USERID not between", value1, value2, "mthUserid");
            return (Criteria) this;
        }

        public Criteria andMthTermNoIsNull() {
            addCriterion("MTH_TERM_NO is null");
            return (Criteria) this;
        }

        public Criteria andMthTermNoIsNotNull() {
            addCriterion("MTH_TERM_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMthTermNoEqualTo(String value) {
            addCriterion("MTH_TERM_NO =", value, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoNotEqualTo(String value) {
            addCriterion("MTH_TERM_NO <>", value, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoGreaterThan(String value) {
            addCriterion("MTH_TERM_NO >", value, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_TERM_NO >=", value, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoLessThan(String value) {
            addCriterion("MTH_TERM_NO <", value, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoLessThanOrEqualTo(String value) {
            addCriterion("MTH_TERM_NO <=", value, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoLike(String value) {
            addCriterion("MTH_TERM_NO like", value, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoNotLike(String value) {
            addCriterion("MTH_TERM_NO not like", value, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoIn(List<String> values) {
            addCriterion("MTH_TERM_NO in", values, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoNotIn(List<String> values) {
            addCriterion("MTH_TERM_NO not in", values, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoBetween(String value1, String value2) {
            addCriterion("MTH_TERM_NO between", value1, value2, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthTermNoNotBetween(String value1, String value2) {
            addCriterion("MTH_TERM_NO not between", value1, value2, "mthTermNo");
            return (Criteria) this;
        }

        public Criteria andMthRCodeIsNull() {
            addCriterion("MTH_R_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMthRCodeIsNotNull() {
            addCriterion("MTH_R_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMthRCodeEqualTo(String value) {
            addCriterion("MTH_R_CODE =", value, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeNotEqualTo(String value) {
            addCriterion("MTH_R_CODE <>", value, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeGreaterThan(String value) {
            addCriterion("MTH_R_CODE >", value, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_R_CODE >=", value, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeLessThan(String value) {
            addCriterion("MTH_R_CODE <", value, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeLessThanOrEqualTo(String value) {
            addCriterion("MTH_R_CODE <=", value, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeLike(String value) {
            addCriterion("MTH_R_CODE like", value, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeNotLike(String value) {
            addCriterion("MTH_R_CODE not like", value, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeIn(List<String> values) {
            addCriterion("MTH_R_CODE in", values, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeNotIn(List<String> values) {
            addCriterion("MTH_R_CODE not in", values, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeBetween(String value1, String value2) {
            addCriterion("MTH_R_CODE between", value1, value2, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthRCodeNotBetween(String value1, String value2) {
            addCriterion("MTH_R_CODE not between", value1, value2, "mthRCode");
            return (Criteria) this;
        }

        public Criteria andMthTransidIsNull() {
            addCriterion("MTH_TRANSID is null");
            return (Criteria) this;
        }

        public Criteria andMthTransidIsNotNull() {
            addCriterion("MTH_TRANSID is not null");
            return (Criteria) this;
        }

        public Criteria andMthTransidEqualTo(String value) {
            addCriterion("MTH_TRANSID =", value, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidNotEqualTo(String value) {
            addCriterion("MTH_TRANSID <>", value, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidGreaterThan(String value) {
            addCriterion("MTH_TRANSID >", value, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_TRANSID >=", value, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidLessThan(String value) {
            addCriterion("MTH_TRANSID <", value, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidLessThanOrEqualTo(String value) {
            addCriterion("MTH_TRANSID <=", value, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidLike(String value) {
            addCriterion("MTH_TRANSID like", value, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidNotLike(String value) {
            addCriterion("MTH_TRANSID not like", value, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidIn(List<String> values) {
            addCriterion("MTH_TRANSID in", values, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidNotIn(List<String> values) {
            addCriterion("MTH_TRANSID not in", values, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidBetween(String value1, String value2) {
            addCriterion("MTH_TRANSID between", value1, value2, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransidNotBetween(String value1, String value2) {
            addCriterion("MTH_TRANSID not between", value1, value2, "mthTransid");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeIsNull() {
            addCriterion("MTH_TRANS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeIsNotNull() {
            addCriterion("MTH_TRANS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeEqualTo(String value) {
            addCriterion("MTH_TRANS_TYPE =", value, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeNotEqualTo(String value) {
            addCriterion("MTH_TRANS_TYPE <>", value, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeGreaterThan(String value) {
            addCriterion("MTH_TRANS_TYPE >", value, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_TRANS_TYPE >=", value, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeLessThan(String value) {
            addCriterion("MTH_TRANS_TYPE <", value, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeLessThanOrEqualTo(String value) {
            addCriterion("MTH_TRANS_TYPE <=", value, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeLike(String value) {
            addCriterion("MTH_TRANS_TYPE like", value, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeNotLike(String value) {
            addCriterion("MTH_TRANS_TYPE not like", value, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeIn(List<String> values) {
            addCriterion("MTH_TRANS_TYPE in", values, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeNotIn(List<String> values) {
            addCriterion("MTH_TRANS_TYPE not in", values, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeBetween(String value1, String value2) {
            addCriterion("MTH_TRANS_TYPE between", value1, value2, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthTransTypeNotBetween(String value1, String value2) {
            addCriterion("MTH_TRANS_TYPE not between", value1, value2, "mthTransType");
            return (Criteria) this;
        }

        public Criteria andMthChannelIsNull() {
            addCriterion("MTH_CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andMthChannelIsNotNull() {
            addCriterion("MTH_CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andMthChannelEqualTo(String value) {
            addCriterion("MTH_CHANNEL =", value, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelNotEqualTo(String value) {
            addCriterion("MTH_CHANNEL <>", value, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelGreaterThan(String value) {
            addCriterion("MTH_CHANNEL >", value, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_CHANNEL >=", value, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelLessThan(String value) {
            addCriterion("MTH_CHANNEL <", value, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelLessThanOrEqualTo(String value) {
            addCriterion("MTH_CHANNEL <=", value, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelLike(String value) {
            addCriterion("MTH_CHANNEL like", value, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelNotLike(String value) {
            addCriterion("MTH_CHANNEL not like", value, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelIn(List<String> values) {
            addCriterion("MTH_CHANNEL in", values, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelNotIn(List<String> values) {
            addCriterion("MTH_CHANNEL not in", values, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelBetween(String value1, String value2) {
            addCriterion("MTH_CHANNEL between", value1, value2, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthChannelNotBetween(String value1, String value2) {
            addCriterion("MTH_CHANNEL not between", value1, value2, "mthChannel");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidIsNull() {
            addCriterion("MTH_EXTERNAL_TXNID is null");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidIsNotNull() {
            addCriterion("MTH_EXTERNAL_TXNID is not null");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidEqualTo(String value) {
            addCriterion("MTH_EXTERNAL_TXNID =", value, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidNotEqualTo(String value) {
            addCriterion("MTH_EXTERNAL_TXNID <>", value, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidGreaterThan(String value) {
            addCriterion("MTH_EXTERNAL_TXNID >", value, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_EXTERNAL_TXNID >=", value, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidLessThan(String value) {
            addCriterion("MTH_EXTERNAL_TXNID <", value, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidLessThanOrEqualTo(String value) {
            addCriterion("MTH_EXTERNAL_TXNID <=", value, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidLike(String value) {
            addCriterion("MTH_EXTERNAL_TXNID like", value, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidNotLike(String value) {
            addCriterion("MTH_EXTERNAL_TXNID not like", value, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidIn(List<String> values) {
            addCriterion("MTH_EXTERNAL_TXNID in", values, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidNotIn(List<String> values) {
            addCriterion("MTH_EXTERNAL_TXNID not in", values, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidBetween(String value1, String value2) {
            addCriterion("MTH_EXTERNAL_TXNID between", value1, value2, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidNotBetween(String value1, String value2) {
            addCriterion("MTH_EXTERNAL_TXNID not between", value1, value2, "mthExternalTxnid");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerIsNull() {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER is null");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerIsNotNull() {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerEqualTo(String value) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER =", value, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerNotEqualTo(String value) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER <>", value, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerGreaterThan(String value) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER >", value, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER >=", value, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerLessThan(String value) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER <", value, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerLessThanOrEqualTo(String value) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER <=", value, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerLike(String value) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER like", value, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerNotLike(String value) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER not like", value, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerIn(List<String> values) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER in", values, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerNotIn(List<String> values) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER not in", values, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerBetween(String value1, String value2) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER between", value1, value2, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthExternalTxnidOwnerNotBetween(String value1, String value2) {
            addCriterion("MTH_EXTERNAL_TXNID_OWNER not between", value1, value2, "mthExternalTxnidOwner");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdIsNull() {
            addCriterion("MTH_TRANS_ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdIsNotNull() {
            addCriterion("MTH_TRANS_ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdEqualTo(String value) {
            addCriterion("MTH_TRANS_ORDER_ID =", value, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdNotEqualTo(String value) {
            addCriterion("MTH_TRANS_ORDER_ID <>", value, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdGreaterThan(String value) {
            addCriterion("MTH_TRANS_ORDER_ID >", value, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_TRANS_ORDER_ID >=", value, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdLessThan(String value) {
            addCriterion("MTH_TRANS_ORDER_ID <", value, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdLessThanOrEqualTo(String value) {
            addCriterion("MTH_TRANS_ORDER_ID <=", value, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdLike(String value) {
            addCriterion("MTH_TRANS_ORDER_ID like", value, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdNotLike(String value) {
            addCriterion("MTH_TRANS_ORDER_ID not like", value, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdIn(List<String> values) {
            addCriterion("MTH_TRANS_ORDER_ID in", values, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdNotIn(List<String> values) {
            addCriterion("MTH_TRANS_ORDER_ID not in", values, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdBetween(String value1, String value2) {
            addCriterion("MTH_TRANS_ORDER_ID between", value1, value2, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthTransOrderIdNotBetween(String value1, String value2) {
            addCriterion("MTH_TRANS_ORDER_ID not between", value1, value2, "mthTransOrderId");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationIsNull() {
            addCriterion("MTH_CASHIER_INFORMATION is null");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationIsNotNull() {
            addCriterion("MTH_CASHIER_INFORMATION is not null");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationEqualTo(String value) {
            addCriterion("MTH_CASHIER_INFORMATION =", value, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationNotEqualTo(String value) {
            addCriterion("MTH_CASHIER_INFORMATION <>", value, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationGreaterThan(String value) {
            addCriterion("MTH_CASHIER_INFORMATION >", value, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_CASHIER_INFORMATION >=", value, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationLessThan(String value) {
            addCriterion("MTH_CASHIER_INFORMATION <", value, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationLessThanOrEqualTo(String value) {
            addCriterion("MTH_CASHIER_INFORMATION <=", value, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationLike(String value) {
            addCriterion("MTH_CASHIER_INFORMATION like", value, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationNotLike(String value) {
            addCriterion("MTH_CASHIER_INFORMATION not like", value, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationIn(List<String> values) {
            addCriterion("MTH_CASHIER_INFORMATION in", values, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationNotIn(List<String> values) {
            addCriterion("MTH_CASHIER_INFORMATION not in", values, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationBetween(String value1, String value2) {
            addCriterion("MTH_CASHIER_INFORMATION between", value1, value2, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthCashierInformationNotBetween(String value1, String value2) {
            addCriterion("MTH_CASHIER_INFORMATION not between", value1, value2, "mthCashierInformation");
            return (Criteria) this;
        }

        public Criteria andMthRrnIsNull() {
            addCriterion("MTH_RRN is null");
            return (Criteria) this;
        }

        public Criteria andMthRrnIsNotNull() {
            addCriterion("MTH_RRN is not null");
            return (Criteria) this;
        }

        public Criteria andMthRrnEqualTo(String value) {
            addCriterion("MTH_RRN =", value, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnNotEqualTo(String value) {
            addCriterion("MTH_RRN <>", value, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnGreaterThan(String value) {
            addCriterion("MTH_RRN >", value, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_RRN >=", value, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnLessThan(String value) {
            addCriterion("MTH_RRN <", value, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnLessThanOrEqualTo(String value) {
            addCriterion("MTH_RRN <=", value, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnLike(String value) {
            addCriterion("MTH_RRN like", value, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnNotLike(String value) {
            addCriterion("MTH_RRN not like", value, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnIn(List<String> values) {
            addCriterion("MTH_RRN in", values, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnNotIn(List<String> values) {
            addCriterion("MTH_RRN not in", values, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnBetween(String value1, String value2) {
            addCriterion("MTH_RRN between", value1, value2, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthRrnNotBetween(String value1, String value2) {
            addCriterion("MTH_RRN not between", value1, value2, "mthRrn");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateIsNull() {
            addCriterion("MTH_SETTLE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateIsNotNull() {
            addCriterion("MTH_SETTLE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateEqualTo(String value) {
            addCriterion("MTH_SETTLE_DATE =", value, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateNotEqualTo(String value) {
            addCriterion("MTH_SETTLE_DATE <>", value, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateGreaterThan(String value) {
            addCriterion("MTH_SETTLE_DATE >", value, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateGreaterThanOrEqualTo(String value) {
            addCriterion("MTH_SETTLE_DATE >=", value, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateLessThan(String value) {
            addCriterion("MTH_SETTLE_DATE <", value, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateLessThanOrEqualTo(String value) {
            addCriterion("MTH_SETTLE_DATE <=", value, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateLike(String value) {
            addCriterion("MTH_SETTLE_DATE like", value, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateNotLike(String value) {
            addCriterion("MTH_SETTLE_DATE not like", value, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateIn(List<String> values) {
            addCriterion("MTH_SETTLE_DATE in", values, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateNotIn(List<String> values) {
            addCriterion("MTH_SETTLE_DATE not in", values, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateBetween(String value1, String value2) {
            addCriterion("MTH_SETTLE_DATE between", value1, value2, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andMthSettleDateNotBetween(String value1, String value2) {
            addCriterion("MTH_SETTLE_DATE not between", value1, value2, "mthSettleDate");
            return (Criteria) this;
        }

        public Criteria andIssuerIdIsNull() {
            addCriterion("ISSUER_ID is null");
            return (Criteria) this;
        }

        public Criteria andIssuerIdIsNotNull() {
            addCriterion("ISSUER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIssuerIdEqualTo(String value) {
            addCriterion("ISSUER_ID =", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdNotEqualTo(String value) {
            addCriterion("ISSUER_ID <>", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdGreaterThan(String value) {
            addCriterion("ISSUER_ID >", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUER_ID >=", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdLessThan(String value) {
            addCriterion("ISSUER_ID <", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdLessThanOrEqualTo(String value) {
            addCriterion("ISSUER_ID <=", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdLike(String value) {
            addCriterion("ISSUER_ID like", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdNotLike(String value) {
            addCriterion("ISSUER_ID not like", value, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdIn(List<String> values) {
            addCriterion("ISSUER_ID in", values, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdNotIn(List<String> values) {
            addCriterion("ISSUER_ID not in", values, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdBetween(String value1, String value2) {
            addCriterion("ISSUER_ID between", value1, value2, "issuerId");
            return (Criteria) this;
        }

        public Criteria andIssuerIdNotBetween(String value1, String value2) {
            addCriterion("ISSUER_ID not between", value1, value2, "issuerId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CULSITE.M_TRANS_HEADER
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}